export const GET_CONTENTS_REQUEST = 'GET_CONTENTS_REQUEST';
export const GET_CONTENTS_SUCCESS = 'GET_CONTENTS_SUCCESS';
export const GET_CONTENTS_ERROR = 'GET_CONTENTS_ERROR';
export const GET_CONTENT = 'GET_CONTENT';
export const TYPE_FILTER = 'TYPE_FILTER';
export const SEARCH_FILTER = 'SEARCH_FILTER';